package com.hamza.studyhub.webuntis

import de.keule.webuntis.WebUntis
import de.keule.webuntis.WebUntisRequestManager
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import java.time.format.DateTimeFormatter

/**
 * Reads Hamza's homework directly from WebUntis using the QR/secret credentials
 * generated by WebUntis itself. The secret is used only on the device.
 */
class WebUntisClient(private val config: WebUntisConfig) {

    data class Homework(
        val id: Long,
        val lessonId: Long,
        val assignedDate: Int,
        val dueDate: Int,
        val text: String,
        val remark: String,
        val completed: Boolean,
        val subject: String,
        val teacher: String
    )

    fun fetchHomeworks(start: LocalDate, end: LocalDate): List<Homework> {
        val untis = WebUntis(
            config.user,
            config.secret,
            config.school,
            config.server,
            true
        )

        if (!untis.login()) {
            throw IllegalStateException("تعذر تسجيل الدخول إلى WebUntis")
        }

        return try {
            val formatter = DateTimeFormatter.BASIC_ISO_DATE
            val endpoint = "WebUntis/api/homeworks/lessons?startDate=${start.format(formatter)}&endDate=${end.format(formatter)}"
            val response = WebUntisRequestManager.requestGET(untis.sessionInfo, endpoint)

            if (response.hasError()) {
                throw IllegalStateException(response.completeErrorMessage)
            }

            parseHomeworkResponse(response.response)
        } finally {
            runCatching { untis.logout() }
        }
    }

    private fun parseHomeworkResponse(root: JSONObject): List<Homework> {
        val data = root.optJSONObject("data") ?: root
        val homeworks = data.optJSONArray("homeworks") ?: JSONArray()
        val lessons = data.optJSONArray("lessons") ?: JSONArray()
        val records = data.optJSONArray("records") ?: JSONArray()
        val teachers = data.optJSONArray("teachers") ?: JSONArray()

        val lessonsById = mutableMapOf<Long, JSONObject>()
        for (i in 0 until lessons.length()) {
            val lesson = lessons.optJSONObject(i) ?: continue
            lessonsById[lesson.optLong("id", Long.MIN_VALUE)] = lesson
        }

        val teachersById = mutableMapOf<Long, JSONObject>()
        for (i in 0 until teachers.length()) {
            val teacher = teachers.optJSONObject(i) ?: continue
            teachersById[teacher.optLong("id", Long.MIN_VALUE)] = teacher
        }

        val teacherByHomeworkId = mutableMapOf<Long, Long>()
        for (i in 0 until records.length()) {
            val record = records.optJSONObject(i) ?: continue
            val homeworkId = record.optLong("homeworkId", Long.MIN_VALUE)
            val teacherId = record.optLong("teacherId", Long.MIN_VALUE)
            if (homeworkId != Long.MIN_VALUE && teacherId != Long.MIN_VALUE) {
                teacherByHomeworkId[homeworkId] = teacherId
            }
        }

        val result = mutableListOf<Homework>()
        for (i in 0 until homeworks.length()) {
            val hw = homeworks.optJSONObject(i) ?: continue
            val id = hw.optLong("id", Long.MIN_VALUE)
            if (id == Long.MIN_VALUE) continue

            val lessonId = hw.optLong("lessonId", Long.MIN_VALUE)
            val lesson = lessonsById[lessonId]
            val teacher = teacherByHomeworkId[id]?.let { teachersById[it] }

            result += Homework(
                id = id,
                lessonId = lessonId,
                assignedDate = hw.optInt("date", 0),
                dueDate = hw.optInt("dueDate", 0),
                text = hw.optString("text").trim(),
                remark = hw.optString("remark").trim(),
                completed = hw.optBoolean("completed", false),
                subject = extractSubject(lesson),
                teacher = extractTeacher(teacher)
            )
        }

        return result
    }

    private fun extractSubject(lesson: JSONObject?): String {
        lesson ?: return ""
        val raw = lesson.opt("subject")
        if (raw is String && raw.isNotBlank()) return raw
        if (raw is JSONObject) {
            raw.optString("longName").takeIf { it.isNotBlank() }?.let { return it }
            raw.optString("name").takeIf { it.isNotBlank() }?.let { return it }
        }
        listOf("subjectName", "subjectLongName").forEach { key ->
            lesson.optString(key).takeIf { it.isNotBlank() }?.let { return it }
        }
        return ""
    }

    private fun extractTeacher(teacher: JSONObject?): String {
        teacher ?: return ""
        listOf("longName", "displayName", "name").forEach { key ->
            teacher.optString(key).takeIf { it.isNotBlank() }?.let { return it }
        }
        return ""
    }
}
